### ISSUE TITLE
Establecer la meta del sistema a largo plazo

### ISSUE THREAD

**Issue by AlbertoBermea** [ProyectoIntegrador2018/blue-lab#7]
### Descripción

Definir la meta de porque se esta haciendo este proyecto desde un inicio, donde queremos estar en seis meses, un año o cinco años?

Definir preguntas del sprint
Que se va responder al final de la semana?
Que se tiene que hacer para cumplir con la meta del sistema?

### Listado de tareas

- [x] Definir meta del sistema
- [x] Definir preguntas del sprint

### Definition of Done

- [x] ¿Se tiene una buena meta para trabajar con esta en mente durante la semana?

**Comment by Doigo12** [comment]
La deficion de la meta se encuentra en la documentacion del proyecto.
